package com.imontalvodev.beatmybeat.shared.youtube

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

class YouTubeInputParsingTest {

    private val videoId = "dQw4w9WgXcQ"

    @Test
    fun nonUrlInputIsInvalid() {
        assertEquals(ParsedYouTubeInput.Invalid(InvalidReason.Format), parseYouTubeInput("not a url"))
    }

    @Test
    fun disallowedHostIsInvalid() {
        val result = parseYouTubeInput("https://example.com/watch?v=$videoId")
        assertEquals(ParsedYouTubeInput.Invalid(InvalidReason.HostNotAllowed), result)
    }

    @Test
    fun watchUrlResolvesToSingleSong() {
        assertEquals(ParsedYouTubeInput.SingleSong(videoId), parseYouTubeInput("https://www.youtube.com/watch?v=$videoId"))
    }

    @Test
    fun youtuBeShortUrlResolvesToSingleSong() {
        assertEquals(ParsedYouTubeInput.SingleSong(videoId), parseYouTubeInput("https://youtu.be/$videoId"))
    }

    @Test
    fun urlWithoutSchemeIsAccepted() {
        assertEquals(ParsedYouTubeInput.SingleSong(videoId), parseYouTubeInput("youtu.be/$videoId"))
        assertEquals(ParsedYouTubeInput.SingleSong(videoId), parseYouTubeInput("www.youtube.com/watch?v=$videoId"))
    }

    @Test
    fun shortsLiveAndEmbedUrlsResolveToSingleSong() {
        listOf("shorts", "live", "embed").forEach { kind ->
            assertEquals(
                ParsedYouTubeInput.SingleSong(videoId),
                parseYouTubeInput("https://www.youtube.com/$kind/$videoId"),
                kind,
            )
        }
    }

    @Test
    fun musicHostIsAllowed() {
        assertEquals(ParsedYouTubeInput.SingleSong(videoId), parseYouTubeInput("https://music.youtube.com/watch?v=$videoId"))
    }

    @Test
    fun playlistUrlResolvesToPlaylist() {
        val result = parseYouTubeInput("https://www.youtube.com/playlist?list=PL1234567890")
        assertTrue(result is ParsedYouTubeInput.PlaylistOrAlbum)
        assertEquals("PL1234567890", result.listId)
        assertEquals("https://www.youtube.com/playlist?list=PL1234567890", result.url)
    }

    @Test
    fun listParameterTakesPriorityOverVideo() {
        val result = parseYouTubeInput("https://www.youtube.com/watch?v=$videoId&list=PL1234567890")
        assertTrue(result is ParsedYouTubeInput.PlaylistOrAlbum)
        assertEquals("PL1234567890", result.listId)
        assertTrue(result.url.contains(videoId))
    }

    @Test
    fun autoGeneratedMixWithVideoResolvesToTheSong() {
        val result = parseYouTubeInput("https://www.youtube.com/watch?v=$videoId&list=RD$videoId&start_radio=1")
        assertEquals(ParsedYouTubeInput.SingleSong(videoId), result)
    }

    @Test
    fun youtubeHomePageIsUnsupported() {
        assertEquals(ParsedYouTubeInput.Invalid(InvalidReason.Unsupported), parseYouTubeInput("https://www.youtube.com/"))
    }

    @Test
    fun extractVideoIdRejectsWrongLengthOrCharacters() {
        assertNull(extractYouTubeVideoId("https://www.youtube.com/watch?v=tooShort"))
        assertNull(extractYouTubeVideoId("https://www.youtube.com/watch?v=dQw4w9WgX!Q"))
    }

    @Test
    fun extractVideoIdFromLiveSegment() {
        assertEquals(videoId, extractYouTubeVideoId("https://www.youtube.com/live/$videoId"))
    }
}
