package com.imontalvodev.beatmybeat.shared.youtube

import io.ktor.http.URLBuilder
import io.ktor.http.URLProtocol
import io.ktor.http.Url

sealed interface ParsedYouTubeInput {
    data class PlaylistOrAlbum(val url: String, val listId: String) : ParsedYouTubeInput
    data class SingleSong(val videoId: String) : ParsedYouTubeInput
    data class Invalid(val reason: InvalidReason) : ParsedYouTubeInput
}

enum class InvalidReason { Format, HostNotAllowed, Unsupported }

private val ALLOWED_HOSTS = setOf("youtube.com", "m.youtube.com", "music.youtube.com", "youtu.be")
private val VIDEO_ID = Regex("^[A-Za-z0-9_-]{11}$")

/**
 * Listas "Mix" / radio (`RD…`) que YouTube genera al vuelo: no son una playlist descargable. Si
 * el enlace trae un vídeo, lo que el usuario quiere es esa canción.
 */
private fun isAutoGeneratedMix(listId: String) = listId.startsWith("RD")

fun parseYouTubeInput(raw: String): ParsedYouTubeInput {
    val input = raw.trim()
    if (input.isEmpty() || input.any { it.isWhitespace() }) {
        return ParsedYouTubeInput.Invalid(InvalidReason.Format)
    }
    // Es habitual pegar "youtu.be/…" o "youtube.com/watch?v=…" sin esquema.
    val withScheme = if ("://" in input) input else "https://$input"
    val url = runCatching { Url(withScheme) }.getOrNull()
        ?.takeIf { it.protocol == URLProtocol.HTTPS || it.protocol == URLProtocol.HTTP }
        ?.takeIf { it.host.isNotBlank() }
        ?: return ParsedYouTubeInput.Invalid(InvalidReason.Format)

    val host = url.host.lowercase().removePrefix("www.")
    if (host !in ALLOWED_HOSTS) return ParsedYouTubeInput.Invalid(InvalidReason.HostNotAllowed)

    val videoId = extractYouTubeVideoId(url)
    val listId = url.parameters["list"]?.trim().orEmpty()
    if (listId.isNotBlank() && !(isAutoGeneratedMix(listId) && videoId != null)) {
        return ParsedYouTubeInput.PlaylistOrAlbum(canonicalPlaylistUrl(listId, videoId), listId)
    }
    if (videoId != null) return ParsedYouTubeInput.SingleSong(videoId)
    return ParsedYouTubeInput.Invalid(InvalidReason.Unsupported)
}

private fun canonicalPlaylistUrl(listId: String, videoId: String?): String =
    URLBuilder("https://www.youtube.com/playlist").apply {
        parameters.append("list", listId)
        // youtu.be/<id>?list=… conserva el vídeo para poder resolver la canción concreta.
        if (videoId != null) parameters.append("v", videoId)
    }.buildString()

fun extractYouTubeVideoId(url: Url): String? {
    val host = url.host.lowercase().removePrefix("www.")
    val segments = url.segments
    val candidate = when {
        host == "youtu.be" -> segments.firstOrNull()
        segments.firstOrNull() == "watch" -> url.parameters["v"]?.trim()
        segments.size >= 2 && segments[0] in setOf("shorts", "live", "embed") -> segments[1]
        else -> null
    }
    return candidate?.takeIf { VIDEO_ID.matches(it) }
}

fun extractYouTubeVideoId(raw: String): String? =
    runCatching { Url(raw.trim()) }.getOrNull()?.let(::extractYouTubeVideoId)
